refactor: move initialization of metadata into post_checkout hook

diff --git a/image/hooks/post_checkout b/image/hooks/post_checkout
--- a/image/hooks/post_checkout
+++ b/image/hooks/post_checkout
@@ -1,1 +1,29 @@
-print-name
+set -eua
+
+IMAGE_VENDOR="${IMAGE_VENDOR}"
+IMAGE_TITLE="${DOCKER_REPO}"
+IMAGE_VERSION="${DOCKER_TAG}"
+IMAGE_REVISION="${SOURCE_COMMIT}"
+IMAGE_CREATED="$(date -u --rfc-3339 seconds)"
+IMAGE_REF_NAME="${SOURCE_BRANCH}"
+
+if ! command -v jq >/dev/null; then
+    >&2 echo 'Ignoring GitHub metadata because of missing required dependency "jq".'
+else
+    github_metadata_url="https://api.github.com/repos/${IMAGE_VENDOR}/${IMAGE_TITLE}"
+    if wget -q --spider "${github_metadata_url}"; then
+        GITHUB_REPO_METADATA=$(wget -q -O - "${github_metadata_url}")
+
+        GITHUB_OWNER_NAME="$( echo "${GITHUB_REPO_METADATA}" | jq -r '.owner.login     // empty')"
+        GITHUB_OWNER_URL="$(  echo "${GITHUB_REPO_METADATA}" | jq -r '.owner.html_url  // empty')"
+        GITHUB_URL="$(        echo "${GITHUB_REPO_METADATA}" | jq -r '.html_url        // empty')"
+        GITHUB_DESCRIPTION="$(echo "${GITHUB_REPO_METADATA}" | jq -r '.description     // empty')"
+        GITHUB_LICENSE="$(    echo "${GITHUB_REPO_METADATA}" | jq -r '.license.spdx_id // empty')"
+
+        IMAGE_DESCRIPTION="${GITHUB_DESCRIPTION}"
+        IMAGE_URL="${GITHUB_URL}"
+        IMAGE_DOCUMENTATION="${IMAGE_URL:+${IMAGE_URL}#readme}"
+        IMAGE_LICENSES="${GITHUB_LICENSE}"
+        IMAGE_AUTHORS="${GITHUB_OWNER_URL}"
+    fi
+fi
